const API_BASE_URL = 'https://avl-frontend-exam.herokuapp.com'

const GET_SEARCH_REQUEST = 'GET_SEARCH_REQUEST'
const GET_SEARCH_SUCCESS = 'GET_SEARCH_SUCCESS'
const GET_SEARCH_FAIL = 'GET_SEARCH_FAIL'

const GET_FOLLOWERS_REQUEST = 'GET_FOLLOWERS_REQUEST'
const GET_FOLLOWERS_SUCCESS = 'GET_FOLLOWERS_SUCCESS'
const GET_FOLLOWERS_FAIL = 'GET_FOLLOWERS_FAIL'

const GET_FOLLOWING_REQUEST = 'GET_FOLLOWING_REQUEST'
const GET_FOLLOWING_SUCCESS = 'GET_FOLLOWING_SUCCESS'
const GET_FOLLOWING_FAIL = 'GET_FOLLOWING_FAIL'

const GET_TAGS_REQUEST = 'GET_TAGS_REQUEST'
const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS'
const GET_TAGS_FAIL = 'GET_TAGS_FAIL'

export {
  API_BASE_URL,
  GET_SEARCH_REQUEST,
  GET_SEARCH_SUCCESS,
  GET_SEARCH_FAIL,
  GET_FOLLOWERS_REQUEST,
  GET_FOLLOWERS_SUCCESS,
  GET_FOLLOWERS_FAIL,
  GET_FOLLOWING_REQUEST,
  GET_FOLLOWING_SUCCESS,
  GET_FOLLOWING_FAIL,
  GET_TAGS_REQUEST,
  GET_TAGS_SUCCESS,
  GET_TAGS_FAIL,
}
